CCM-12869:  Implement event builder for supplier config events (#38)
* Feature: Add initial schemas and events for supplier configuration

* Fix: dependencies

* Remove domain prefix from subject in event envelope

* Remove documentation examples
+ fix event-builder tests

* Remove generated files from git

* Add contract events

* Remove stray readme

* Add supplier model events

* Refactor contract references to volume group in schemas and events

* Add volume group events and update JSON generation

* Refactor status handling to use $EnvironmentStatus across configurations

* Update tests

* Add approval status validation and update enums in specifications

* Update deliverySLA to deliveryDays and change status references to PROD

* Refactor colour property to restrict to WHITE and update description

* Add DISABLED status to various entities and update related schemas

* Add optional description to PackSpecification and update tests

* Add duplex field validation to PackSpecification and update tests

* Add ATTACHMENT type to PackSpecification $Insert schema

* Add constraints validation to PackSpecification and related tests

* Rename specification-supplier.test.ts to supplier-pack.test.ts

* Enhance constraint validation by adding GREATER_THAN_OR_EQUAL and LESS_THAN_OR_EQUAL options; update billingId metadata in PackSpecification

* Event Builder: tools for constructing valid config events from payload data

* Remove content that lives on other branches

* Refactor event builder tests to remove unnecessary imports and use string literals for VolumeGroupId

* Add billingId to PackSpecification in event builder tests
+ remove redundant CLI tool and libs

* Add billingId to specification in event builder tests

* Add billingId to PackSpecification examples in specification-examples.ts

* Update package-lock.json to upgrade js-yaml, diff, and glob dependencies

* Add AsyncAPI bundling and event schema package publishing

* Update documentation for event-builder package and clarify CloudEvent functions

* Add script to validate version increments for packages

* Bump schema patch version (changes to examples and asyncapi bundling, but no schema changes)

* Refactor imports in volume-group-event-builder.ts and update jest.config.ts for module mapping

diff --git a/.github/workflows/stage-1-commit.yaml b/.github/workflows/stage-1-commit.yaml
--- a/.github/workflows/stage-1-commit.yaml
+++ b/.github/workflows/stage-1-commit.yaml
@@ -188,3 +188,107 @@ jobs:
           idp_aws_report_upload_region: "${{ secrets.IDP_AWS_REPORT_UPLOAD_REGION }}"
           idp_aws_report_upload_role_name: "${{ secrets.IDP_AWS_REPORT_UPLOAD_ROLE_NAME }}"
           idp_aws_report_upload_bucket_endpoint: "${{ secrets.IDP_AWS_REPORT_UPLOAD_BUCKET_ENDPOINT }}"
+
+
+  detect-event-schema-package-changes:
+    name: "Check for changes to event schema package compared to main branch"
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+    outputs:
+      changed: ${{ steps.check.outputs.changed }}
+      main_version: ${{ steps.check.outputs.main_version }}
+
+    steps:
+      - name: "Checkout code"
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Detect package changes and current version
+        id: check
+        run: |
+          git fetch origin main
+
+          if git diff --quiet origin/main...HEAD -- packages/events; then
+            echo "No changes in event schemas package"
+            echo "changed=false" >> $GITHUB_OUTPUT
+          else
+            echo "Changes detected in event schemas"
+            echo "changed=true" >> $GITHUB_OUTPUT
+          fi
+
+          if content=$(git show origin/main:packages/events/package.json 2>/dev/null); then
+            version=$(jq -r .version <<< $content);
+          else
+            version=null;
+          fi
+
+          echo "Detected package version $version in main branch"
+          echo "main_version=$version" >> $GITHUB_OUTPUT
+
+  check-schema-version-change:
+    name: Check event schema version has been updated
+    needs: detect-event-schema-package-changes
+    if: needs.detect-event-schema-package-changes.outputs.changed == 'true'
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Check schema versions
+        run: |
+          source scripts/is_valid_increment.sh
+
+          main_version="${{ needs.detect-event-schema-package-changes.outputs.main_version }}"
+          echo "Main version: ${{ needs.detect-event-schema-package-changes.outputs.main_version }}"
+
+          local_version=$(jq -r '.version' packages/events/package.json)
+          echo "Local version: $local_version"
+
+          if ! is_valid_increment "$main_version" "$local_version" ; then
+            echo "Error: Event Schema package has changed, but new version ($local_version) is not a valid increment from latest version on main branch ($main_version)."
+            exit 1
+          fi
+
+  check-event-schemas-version-change:
+    name: Check for event schemas package version change
+    needs: detect-event-schema-package-changes
+    if: needs.detect-event-schema-package-changes.outputs.changed == 'true'
+    outputs:
+      version_changed: ${{ steps.check-version.outputs.version_changed }}
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      packages: read
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v5.0.0
+
+      - name: Setup NodeJS
+        uses: actions/setup-node@v4
+        with:
+          node-version: ${{ inputs.nodejs_version }}
+          registry-url: "https://npm.pkg.github.com"
+
+      - name: check if local version differs from latest published version
+        id: check-version
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          published_version=$(npm view @nhsdigital/nhs-notify-event-schemas-supplier-config --json 2>/dev/null | jq -r '.["dist-tags"].latest // "null"')
+          echo "Published version: $published_version"
+
+          local_version=$(jq -r '.version' packages/events/package.json)
+          echo "Local version: $local_version"
+
+          if [[ $local_version = $published_version ]]; then
+            echo "ERROR: Local version is the same as the latest published version, but event schemas have changed"
+            echo "version_changed=false" >> $GITHUB_OUTPUT
+            exit 1
+          else
+            echo "Local version is different to the latest published version - a new version will be published"
+            echo "version_changed=true" >> $GITHUB_OUTPUT
+          fi
